/**
 * This file was generated by the Jeddict
 */
package com.udea.tiendamascotas.entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author gaviriza
 */
@Entity
@Table(name = "articulo")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Articulo.findAll", query = "SELECT a FROM Articulo a")
    , @NamedQuery(name = "Articulo.findByIdArticulo", query = "SELECT a FROM Articulo a WHERE a.id_articulo=:id_articulo")
    , @NamedQuery(name = "Articulo.findByNombre", query = "SELECT a FROM Articulo a WHERE a.nombre = :nombre")
    , @NamedQuery(name = "Articulo.findByPrecio", query = "SELECT a FROM Articulo a WHERE a.precio = :precio")
    , @NamedQuery(name = "Articulo.findByFoto", query = "SELECT a FROM Articulo a WHERE a.foto = :foto")
    , @NamedQuery(name = "Articulo.findByEspecie", query = "SELECT a FROM Articulo a WHERE a.especie = :especie")
    , @NamedQuery(name = "Articulo.findByRaza", query = "SELECT a FROM Articulo a WHERE a.raza = :raza")
    , @NamedQuery(name = "Articulo.findByEdad", query = "SELECT a FROM Articulo a WHERE a.edad = :edad")})

public class Articulo implements Serializable {

    @Column(name = "id_articulo", unique = true, nullable = false)
    @Id
    @NotNull(message = "Ingrese un id")
    private Long id_articulo;

    @Column(name = "nombre", nullable = false)
    @Basic
    @NotNull(message = "Ingrese el nombre del articulo")
    private String nombre;

    @Column(name = "precio", nullable = false)
    @Basic
    @NotNull(message = "Ingrese el precio del artÃ­culo")
    private Double precio;

    @Column(name = "foto", nullable = false)
    @Lob
    @Basic
    @NotNull(message = "Ingrese una foto")
    private String foto;

    @Column(name = "especie")
    @Basic
    private String especie;

    @Column(name = "raza")
    @Basic
    private String raza;

    @Column(name = "edad")
    @Basic
    private int edad;

    public Articulo() {
    }

    public Articulo(Long id_articulo, String nombre, Double precio, String foto, String especie, String raza, int edad) {
        this.id_articulo = id_articulo;
        this.nombre = nombre;
        this.precio = precio;
        this.foto = foto;
        this.especie = especie;
        this.raza = raza;
        this.edad = edad;
    }

    public Long getId_articulo() {
        return this.id_articulo;
    }

    public void setId_articulo(Long id_articulo) {
        this.id_articulo = id_articulo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Double getPrecio() {
        return this.precio;
    }

    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    public String getFoto() {
        return this.foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public String getEspecie() {
        return this.especie;
    }

    public void setEspecie(String especie) {
        this.especie = especie;
    }

    public String getRaza() {
        return this.raza;
    }

    public void setRaza(String raza) {
        this.raza = raza;
    }

    public int getEdad() {
        return this.edad;
    }

    public void setEdad(int edad) {
        this.edad = edad;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final Articulo other = (Articulo) obj;
        if (!java.util.Objects.equals(this.getId_articulo(), other.getId_articulo())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + (this.getId_articulo() != null ? this.getId_articulo().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "Articulo{" + " id_articulo=" + id_articulo + ", nombre=" + nombre + ", precio=" + precio + ", foto=" + foto + ", especie=" + especie + ", raza=" + raza + ", edad=" + edad + '}';
    }

}