/**
 * This file was generated by the Jeddict
 */
package com.udea.tiendamascotas.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author gaviriza
 */

@Table(name = "factura")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Factura.findAll", query = "SELECT a FROM Factura a")
    , @NamedQuery(name = "Factura.findByIdArticulo", query = "SELECT a FROM Factura a WHERE a.id_factura = :id_factura")
    , @NamedQuery(name = "Factura.findByNombreComprador", query = "SELECT a FROM Factura a WHERE a.nombre_comprador = :nombre_comprador")
    , @NamedQuery(name = "Factura.findByFecha", query = "SELECT a FROM Factura a WHERE a.fecha = :fecha")
    , @NamedQuery(name = "Automovil.findByPrecio", query = "SELECT a FROM Articulo a WHERE a.foto = :foto")})
@Entity
public class Factura implements Serializable {

    @Column(name = "id_factura", unique = true, nullable = false)
    @Id
    @NotNull(message = "Ingrese un id")
    private Long id_factura;

    @Column(name = "nombre_comprador", nullable = false)
    @Basic
    @NotNull(message = "Ingrese el nombre del comprador")
    private String nombre_comprador;

    @Column(name = "fecha", nullable = false)
    @Basic
    @Temporal(TemporalType.DATE)
    @NotNull(message = "Ingrese una fecha")
    private Date fecha;

    @Column(name = "nombre_vendedor", nullable = false)
    @Basic
    @NotNull(message = "Ingrese el nombre del vendedor")
    private String nombre_vendedor;

    @OneToOne(targetEntity = Venta.class)
    private Venta venta;
    
    private Double precioTotal;

    public Factura(Long id_factura, String nombre_comprador, Date fecha, String nombre_vendedor) {
        this.id_factura = id_factura;
        this.nombre_comprador = nombre_comprador;
        this.fecha = fecha;
        this.nombre_vendedor = nombre_vendedor;
    }

    public void setPrecioTotal(Double precioTotal) {
        this.precioTotal = precioTotal;
    }

    public Double getPrecioTotal() {
        return precioTotal;
    }

    public Factura() {
    }

    public Long getId_factura() {
        return this.id_factura;
    }

    public void setId_factura(Long id_factura) {
        this.id_factura = id_factura;
    }

    public String getNombre_comprador() {
        return this.nombre_comprador;
    }

    public void setNombre_comprador(String nombre_comprador) {
        this.nombre_comprador = nombre_comprador;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getNombre_vendedor() {
        return this.nombre_vendedor;
    }

    public void setNombre_vendedor(String nombre_vendedor) {
        this.nombre_vendedor = nombre_vendedor;
    }

    public Venta getVenta() {
        return this.venta;
    }

    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final Factura other = (Factura) obj;
        if (!java.util.Objects.equals(this.getId_factura(), other.getId_factura())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + (this.getId_factura() != null ? this.getId_factura().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "Factura{" + " id_factura=" + id_factura + ", nombre_comprador=" + nombre_comprador + ", fecha=" + fecha + ", nombre_vendedor=" + nombre_vendedor + '}';
    }

}