/**
 * This file was generated by the Jeddict
 */
package com.udea.tiendamascotas.entity;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

/**
 * @author gaviriza
 */
@Entity(name = "Venta")
public class Venta implements Serializable {

    @Column(name = "id_venta", unique = true, nullable = false)
    @Id
    @NotNull(message = "Ingrese un id")
    private Long id_venta;

    @Column(nullable = false)
    @Basic
    @NotNull(message = "Deben haber articulos comprados para generar una venta")
    private List<Articulo> articulosComprados;

    @OneToMany(targetEntity = Articulo.class)
    private List<Articulo> articulos;

    public Venta() {
    }

    public Venta(Long id_venta) {
        this.id_venta = id_venta;
    }

    public Long getId_venta() {
        return this.id_venta;
    }

    public void setId_venta(Long id_venta) {
        this.id_venta = id_venta;
    }

    public List getArticulosComprados() {
        return this.articulos;
    }

    public void setArticulosComprados(List articulosComprados) {
        this.articulosComprados = articulosComprados;
    }

    public List<Articulo> getArticulos() {
        return this.articulos;
    }

    public void setArticulos(List<Articulo> articulos) {
        this.articulos = articulos;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final Venta other = (Venta) obj;
        if (!java.util.Objects.equals(this.getId_venta(), other.getId_venta())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 37 * hash + (this.getId_venta() != null ? this.getId_venta().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "Venta{" + " id_venta=" + id_venta + '}';
    }

}